### ISSUE TITLE
Permission to reference in drake's documentation?

### ISSUE THREAD

**Issue by wlandau** [joelnitta/pleurosoriopsis#1]
@joelnitta, could I reference this project in `drake`'s documentation?

- https://github.com/ropensci/drake#use-cases
- https://github.com/ropenscilabs/drake-manual/blob/726cd55022322580f7a17d51314c1aa2c50d47c4/index.Rmd#L162-L171
- https://github.com/wlandau/drake-examples#real-world-examples-outside-this-repo

**Comment by wlandau** [comment]
Related: rOpenSci likes to hear about [use cases](https://ropensci.org/usecases/) of its packages. Example: https://discuss.ropensci.org/t/using-drake-to-power-a-new-soil-respiration-database/1692/2.

**Comment by joelnitta** [comment]
Absolutely! Thanks again for the package, and your interest. I will check out rOpenSci's use cases. I've be wanting to be more involved with them, so that could be a good way to get started.

**Comment by wlandau** [comment]
Thanks, @joelnitta! I have added the links.
